/*!
 * @file preconditioner.hpp
 * @brief Block preconditioners for the saddle-point systems assembled in
 *        SaddlePointMat.
 *
 * The classes declared here do not assemble a global preconditioner matrix.
 * Instead, each class stores the sparse factors or diagonal approximations
 * needed to apply P^{-1} inside an iterative method.
 */

// Add this macro to enable the lumping of Mblock in place of taking the
// diagonal part in BlockTr and ILU preconditioners
//#define LUMP

#ifndef __PRECONDITIONER_HPP__
#define __PRECONDITIONER_HPP__

#include "BasicType.hpp"
#include "SaddlePointMat.hpp"
#include <Eigen/LU>
#include <Eigen/SparseCholesky>
#include <unsupported/Eigen/SparseExtra>
#include <memory>

namespace FVCode3D
{
class preconditioner;

//! Typedef for preconPtr_Type
/*!
 * @typedef preconPtr_Type
 * This type definition permits to handle a std::shared_ptr<preconditioner> as a
 * preconPtr_Type.
 */
typedef std::shared_ptr<preconditioner> preconPtr_Type;

//! Build a diagonal approximation of the inverse of the M block.
/*!
 * The approximation is used in all block preconditioners as a cheap surrogate
 * for M^{-1}. Two strategies are available:
 * - diagonal extraction of M
 * - row-sum lumping of |M|
 *
 * @param Mat Saddle-point matrix providing the M block.
 * @param lumping If true, build the inverse of the lumped matrix; otherwise
 * use the inverse of diag(M).
 * @return Diagonal matrix approximating M^{-1}.
 */
DiagMat ComputeApproximateInverseInnerProd(const SaddlePointMat &Mat,
                                           bool lumping = false);

//! Compute the approximate Schur complement T - B D B^T.
/*!
 * Here D approximates M^{-1}; in practice D is generated by
 * ComputeApproximateInverseInnerProd().
 *
 * @param Mat Saddle-point matrix.
 * @param D Diagonal approximation of M^{-1}.
 * @return Sparse approximation of the Schur complement.
 */
SpMat ComputeApproximateSchur(const SaddlePointMat &Mat, const DiagMat &D);

//! Compute the fracture Schur complement used by the double saddle-point form.
/*!
 * The matrix is extracted from the 3x3 block structure produced by
 * SaddlePointMat::convertToDoubleSaddlePoint().
 *
 * @param Mat Double saddle-point matrix.
 * @param D Diagonal approximation of M^{-1}.
 * @return Sparse approximation of the fracture Schur complement.
 */
SpMat ComputeApproximateSchurDSP(const SaddlePointMat &Mat, const DiagMat &D);

//! Compute the B D B^T block appearing in the double saddle-point variant.
/*!
 * @param Mat Double saddle-point matrix.
 * @param D Diagonal approximation of M^{-1}.
 * @return Sparse block acting on cell unknowns.
 */
SpMat BamBt(const SaddlePointMat &Mat, const DiagMat &D);

//! Compute the coupling block B D C^T for the double saddle-point variant.
/*!
 * @param Mat Double saddle-point matrix.
 * @param D Diagonal approximation of M^{-1}.
 * @return Sparse coupling block between cell and fracture subproblems.
 */
SpMat BamCt(const SaddlePointMat &Mat, const DiagMat &D);

//! Convenience overload that internally builds the diagonal M^{-1} surrogate.
/*!
 * @param Mat Saddle-point matrix.
 * @param lumping If true use row-sum lumping, otherwise use diag(M).
 * @return Sparse approximation of the Schur complement.
 */
inline SpMat
ComputeApproximateSchur(const SaddlePointMat &Mat, bool lumping = false)
{
  return ComputeApproximateSchur(
    Mat, ComputeApproximateInverseInnerProd(Mat, lumping));
}
//! Abstract interface for all saddle-point preconditioners used in this folder.
/*!
 * @class preconditioner
 * Derived classes expose a uniform `set()` + `solve()` API so they can be
 * selected at run time by the factory and passed to the iterative solvers in
 * `IML_Eigen/include`.
 *
 * Implementations store pointers or factorizations derived from the current
 * SaddlePointMat, so the matrix must outlive the preconditioner application.
 */
class preconditioner
{
public:
  //! Assemble or refresh the data needed to apply the preconditioner.
  /*!
   * @param Mat Saddle-point matrix currently used by the solver.
   */
  virtual void set(const SaddlePointMat &Mat) = 0;

  //! @name Solve Methods
  //@{
  //! Apply the preconditioner action z = P^{-1} r.
  /*!
   * @param r Right-hand side vector.
   * @return Preconditioned vector.
   */
  virtual Vector solve(const Vector &r) const = 0;
  /*!
   * Enable row-sum lumping instead of diagonal extraction when approximating
   * M^{-1}.
   */
  void
  setLumping(bool lumping)
  {
    this->lumped = lumping;
  }
  //! To verify if lumping is used instead of diagonal to approximate M
  bool
  lumping() const
  {
    return this->lumped;
  }
  //! @name Set Methods only active in HSS preconditioner
  //@{

  //! Optional parameter hook for HSS-based preconditioners.
  /*!
   * @param Alpha HSS alpha parameter.
   */
  virtual void
  set_alpha(const Real)
  {}

  //! Optional parameter hook for inner iterative solves.
  /*!
   * @param itmax Maximum number of iterations.
   */
  virtual void
  set_MaxIt(const UInt)
  {}

  //! Optional parameter hook for inner iterative solves.
  /*!
   * @param Tol Relative tolerance.
   */
  virtual void
  set_tol(const Real)
  {}
  //@}
  virtual ~preconditioner() = default;

protected:
  bool lumped = false;
  //@}
};

//! Identity preconditioner.
/*!
 * Returns the input residual unchanged. It is useful as a baseline and as a
 * fallback when comparing the impact of the block preconditioners.
 */
class identity_preconditioner : public preconditioner
{
public:
  //! Set the use of the lumped form for the diagonal approximation of M

  identity_preconditioner(const SaddlePointMat &){};
  identity_preconditioner() = default;
  //! Set the preconditioner
  /*!
   * @param Mat The saddle point mat
   */
  void
  set(const SaddlePointMat &) override
  {}
  //! @name Solve Methods
  //@{
  //! Solve the linear system Pz=r
  /*!
   * @param r The rhs vector on what we apply the P^-1
   */
  Vector
  solve(const Vector &r) const override
  {
    return r;
  };
  //@}
};

//! Diagonal block preconditioner using diag(M) and diag(T).
/*!
 * This is the cheapest preconditioner in the file: each block is approximated
 * only through its diagonal entries.
 */
class diagonal_preconditioner : public preconditioner
{
public:
  //! @name Constructor & Destructor
  //@{
  //! Construct a diagonal preconditioner.
  /*!
   * @param Mat The matrix of the system that we want to precondition
   */
  diagonal_preconditioner(const SaddlePointMat &Mat)
    : Mptr(&Mat.getM()), Tptr(&Mat.getT())
  {}
  //! Copy-Constructor deleted
  /*!
   * The reason is that this class is just a wrapper to an existing
   * SaddePointMat. If you activate copy it will be just a shallow copy and
   * this may confuse the user. Better avoid copy constructions
   */
  //! Empty-Constructor
  diagonal_preconditioner() = default;
  //@}

  //! Set the preconditioner
  /*!
   * @param Mat The saddle point mat
   */
  void
  set(const SaddlePointMat &Mat) override
  {
    Mptr = &Mat.getM();
    Tptr = &Mat.getT();
  }

  //! @name Solve Methods
  //@{
  //! Solve the linear system Pz=r
  /*!
   * @param r The rhs vector on what we apply the P^-1
   */
  Vector solve(const Vector &r) const override;
  //@}

private:
  //! A const pointer to the inner product matrix
  const SpMat *Mptr = nullptr;
  //! A const pointer to the T block matrix
  const SpMat *Tptr = nullptr;
};
//! Symmetric block-diagonal preconditioner for the 2x2 saddle-point matrix.
/*!
 * It uses a diagonal approximation of M^{-1} together with a sparse LDLT
 * factorization of the negative Schur complement. The resulting operator is
 * symmetric and is therefore suitable for MINRES.
 */
class BlockDiagonal_preconditioner : public preconditioner
{
public:
  //! @name Constructor & Destructor
  //@{
  BlockDiagonal_preconditioner(const SaddlePointMat &SP) : Bptr{&SP.getB()}
  {
    Md_inv = ComputeApproximateInverseInnerProd(SP, this->lumped);
    chol.compute(-ComputeApproximateSchur(SP, Md_inv));
  }
  //! Empty-Constructor
  BlockDiagonal_preconditioner() = default;
  //@}

  //! @name Assemble Methods
  //@{
  //! Assemble the the inverse diag of M and the SC
  /*!
   * @param Mat The saddle point mat
   *
   */
  void
  set(const SaddlePointMat &SP) override
  {
    Bptr = &SP.getB();
    Md_inv = ComputeApproximateInverseInnerProd(SP, this->lumped);
    // store Chowleski factor of -S
    chol.compute(-ComputeApproximateSchur(SP, Md_inv));
  }
  //@}

  //! @name Solve Methods
  //@{
  //! Solve the linear system Pz=r
  /*!
   * @param r The rhs vector on what we apply the P^-1
   */
  Vector solve(const Vector &r) const override;
  //@}

private:
  //! The B block matrix
  const SpMat *Bptr = nullptr;
  //! The inverse of the diagonal of M
  DiagMat Md_inv;
  //! Cholesky factorization
  Eigen::SimplicialLDLT<SpMat, Eigen::Upper> chol;
};

//! Block-triangular preconditioner for the 2x2 saddle-point matrix.
/*!
 * The M block is approximated by a diagonal inverse, while the pressure block
 * uses the approximate Schur complement.
 */
class BlockTriangular_preconditioner : public preconditioner
{
public:
  //! @name Constructor & Destructor
  //@{
  BlockTriangular_preconditioner(const SaddlePointMat &SP) : Bptr{&SP.getB()}
  {
    Md_inv = ComputeApproximateInverseInnerProd(SP, this->lumped);
    // B D^{-1}B^T -T (-Shur complement)
    chol.compute(-ComputeApproximateSchur(SP, Md_inv));
  }
  BlockTriangular_preconditioner() = default;
  //@}
  //! @name Assemble Methods
  //@{
  //! Assemble the the inverse diag of M and the SC
  /*!
   * @param Mat The saddle point mat
   *
   */
  void
  set(const SaddlePointMat &SP) override
  {
    Bptr = &SP.getB();
    Md_inv = ComputeApproximateInverseInnerProd(SP, this->lumped);
    // -B D^{-1}B^T + T (-Schur complement)
    chol.compute(
      -ComputeApproximateSchur(SP, Md_inv)); // store chowleski factor
  }
  //@}

  //! @name Solve Methods
  //@{
  //! Solve the linear system Pz=r
  /*!
   * @param r The rhs vector on what we apply the P^-1
   */
  Vector solve(const Vector &r) const override;
  //@}

private:
  //! The B block matrix
  const SpMat *Bptr = nullptr;
  //! The inverse of the diagonal of M
  DiagMat Md_inv;
  //! Cholesky factorization
  Eigen::SimplicialLDLT<SpMat, Eigen::Upper> chol;
};

//! Incomplete block LU preconditioner for the 2x2 saddle-point matrix.
/*!
 * The name refers to the block structure, not to Eigen's sparse ILU class:
 * the velocity block is diagonalized and the Schur complement is factorized
 * separately.
 */
class ILU_preconditioner : public preconditioner
{
public:
  //! @name Constructor & Destructor
  //@{
  ILU_preconditioner(const SaddlePointMat &SP) : Bptr{&SP.getB()}
  {
    Md_inv = ComputeApproximateInverseInnerProd(SP, this->lumped);
    // store Chowleski factor of -S
    chol.compute(-ComputeApproximateSchur(SP, Md_inv));
  }
  //@}
  //! Empty-Constructor
  ILU_preconditioner() = default;
  //@}
  //! @name Assemble Methods
  //@{
  //! Assemble the approximations of M and SC
  /*!
   * @param Mat The saddle point mat
   */
  void
  set(const SaddlePointMat &SP) override
  {
    Bptr = &SP.getB();
    Md_inv = ComputeApproximateInverseInnerProd(SP, this->lumped);
    // store Chowleski factor of -S
    chol.compute(-ComputeApproximateSchur(SP, Md_inv));
  }
  //@}

  //! @name Solve Methods
  //@{
  //! Solve the linear system Pz=r
  /*!
   * @param r The rhs vector on what we apply the P^-1
   */
  Vector solve(const Vector &r) const override;
  //@}

private:
  //! The B block matrix
  const SpMat *Bptr = nullptr;
  //! The inverse of the diagonal of M
  DiagMat Md_inv;
  //! Cholesky factorization
  Eigen::SimplicialLDLT<SpMat, Eigen::Upper> chol;
};

//! Hermitian/skew-Hermitian splitting preconditioner.
/*!
 * This variant builds the auxiliary matrices described in the reference paper
 * and applies them through a combination of CG and sparse LDLT solves.
 */
class HSS_preconditioner : public preconditioner
{
public:
  //! @name Constructor & Destructor
  //@{
  HSS_preconditioner(const SaddlePointMat &SP) { this->set(SP); }
  HSS_preconditioner() = default;
  //@}

  //! @name Set Methods
  //@{

  //! Set the max it value for CG
  /*!
   * @param itmax Max it value for CG
   */
  void
  set_alpha(const Real a) override
  {
    alpha = a;
  }

  //! Set the max it value for CG
  /*!
   * @param itmax Max it value for CG
   */
  void
  set_MaxIt(const UInt itmax) override
  {
    MaxIt = itmax;
  }

  //! Set the tolerance value for CG
  /*!
   * @param Tol tolerance value for CG
   */
  void
  set_tol(const Real Tol) override
  {
    tol = Tol;
  }
  //@}

  //! @name Assemble Methods
  //@{
  //! Assemble the approximations of M and SC
  /*!
   * @param SP_Stiff A reference to the saddle point stiffness matrix
   */
  void set(const SaddlePointMat &SP) override;
  //@}

  //! @name Solve Methods
  //@{
  //! Solve the linear system Pz=r
  /*!
   * @param r The rhs vector on what we apply the P^-1
   */
  Vector solve(const Vector &r) const override;
  //@}

private:
  //! A  constant reference to the saddle point matrix
  const SpMat *Bptr = nullptr;
  //! The matrix Halpha
  SpMat Halpha;
  //! The alpha coefficient of the scheme
  Real alpha = alpha_default;
  //! The max it for CG
  UInt MaxIt = MaxIt_default;
  //! The tolerance for CG
  Real tol;
  //! Number of cells
  UInt Ncell;
  //! Number of fracture facets
  UInt Nfrac;
  //! The CG for Halpha
  Eigen::ConjugateGradient<SpMat, Eigen::Lower | Eigen::Upper> cg;
  // Cholesky factorization for Talpha
  Eigen::SimplicialLDLT<SpMat, Eigen::Upper> cholT;
  //! Cholesky factorization for BBtalpha
  Eigen::SimplicialLDLT<SpMat, Eigen::Upper> cholBBt;
  //! Vector to scale M
  Vector scaledM;
  //! The alpha coeff of the scheme (default value)
  inline static constexpr Real alpha_default = 1e-2;
  //! The max it for CG (default value)
  inline static constexpr UInt MaxIt_default = 300;
  //! The tolerance for CG (default value)
  inline static constexpr Real tol_default = 1e-2;
};

class DoubleSaddlePoint_preconditioner : public preconditioner
{
public:
  //! @name Constructor & Destructor
  //@{
  DoubleSaddlePoint_preconditioner(const SaddlePointMat &SP)
    : Bptr{&SP.sparseBlockMatrix().getBlock({1, 0})},
      Cptr{&SP.sparseBlockMatrix().getBlock({2, 0})},
      nVel{SP.sparseBlockMatrix().rows({0, 0})},
      nCell{SP.sparseBlockMatrix().rows({1, 0})}, nFrac{
                                                    SP.sparseBlockMatrix().rows(
                                                      {2, 0})}
  {
    Md_inv = ComputeApproximateInverseInnerProd(SP, this->lumped);
    Schur_chol.compute(ComputeApproximateSchurDSP(SP, Md_inv));
    BAB_chol.compute(BamBt(SP, Md_inv));
    BAmC = BamCt(SP, Md_inv);
  }
  //! Empty-Constructor
  DoubleSaddlePoint_preconditioner() = default;
  //@}

  //! @name Assemble Methods
  //@{
  //! Assemble the the inverse diag of M and the SC
  /*!
   * @param Mat The saddle point mat
   *
   */
  void
  set(const SaddlePointMat &SP) override
  {
    nCell = SP.sparseBlockMatrix().rows({1, 0});
    nVel = SP.sparseBlockMatrix().rows({0, 0});
    nFrac = SP.sparseBlockMatrix().rows({2, 0});
    Bptr = &SP.sparseBlockMatrix().getBlock({1, 0});
    Cptr = &SP.sparseBlockMatrix().getBlock({2, 0});
    Md_inv = ComputeApproximateInverseInnerProd(SP, this->lumped);
    Schur_chol.compute(ComputeApproximateSchurDSP(SP, Md_inv));
    BAB_chol.compute(BamBt(SP, Md_inv));
    BAmC = BamCt(SP, Md_inv);
  }
  //@}

  //! @name Solve Methods
  //@{
  //! Apply the 3x3 block preconditioner after double-saddle-point splitting.
  Vector solve(const Vector &r) const override;
  //@}

protected:
  //! The B block matrix
  const SpMat *Bptr = nullptr;
  const SpMat *Cptr = nullptr;
  SpMat        BAmC;
  Eigen::Index nVel;
  Eigen::Index nCell;
  Eigen::Index nFrac;
  //! The inverse of the diagonal of M
  DiagMat Md_inv;
  //! Cholesky factorization
  Eigen::SimplicialLDLT<SpMat, Eigen::Upper> Schur_chol;
  Eigen::SimplicialLDLT<SpMat, Eigen::Upper> BAB_chol;
};

class DoubleSaddlePointSym_preconditioner
  : public DoubleSaddlePoint_preconditioner
{
public:
  using DoubleSaddlePoint_preconditioner::DoubleSaddlePoint_preconditioner;
  using DoubleSaddlePoint_preconditioner::set;
  //! @name Solve Methods
  //@{
  //! Symmetric variant of the double saddle-point block preconditioner.
  Vector solve(const Vector &r) const override;
  //@}
};

} // namespace FVCode3D

#endif // __LOCAL_OPERATOR_HPP__
