cmake_minimum_required(VERSION 3.20)
include(${CMAKE_CURRENT_LIST_DIR}/PacsCommon.cmake)

function(pacs_collect_sources out_mains out_others)
  file(GLOB SRCS CONFIGURE_DEPENDS "*.cpp")
  set(mains)
  set(others)
  foreach(src IN LISTS SRCS)
    get_filename_component(name "${src}" NAME)
    if(name MATCHES "^main.*\\.cpp$")
      list(APPEND mains "${src}")
    else()
      list(APPEND others "${src}")
    endif()
  endforeach()
  set(${out_mains} "${mains}" PARENT_SCOPE)
  set(${out_others} "${others}" PARENT_SCOPE)
endfunction()

function(pacs_install_headers)
  file(GLOB HDRS CONFIGURE_DEPENDS "*.hpp" "*.h")
  if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/GetPot")
    list(APPEND HDRS "${CMAKE_CURRENT_LIST_DIR}/GetPot")
  endif()
  if(HDRS)
    install(FILES ${HDRS} DESTINATION include)
  endif()
endfunction()

function(pacs_add_example_dir)
  set(options)
  set(one_value_args LIB_NAME PYTHON_MODULE_NAME)
  set(multi_value_args EXPLICIT_MAINS EXPLICIT_OTHERS)
  cmake_parse_arguments(PACS "" "${one_value_args}" "${multi_value_args}" ${ARGN})

  if(PACS_EXPLICIT_MAINS OR PACS_EXPLICIT_OTHERS)
    set(MAINS ${PACS_EXPLICIT_MAINS})
    set(OTHERS ${PACS_EXPLICIT_OTHERS})
  else()
    pacs_collect_sources(MAINS OTHERS)
  endif()

  set(PY_SRCS)
  if(PACS_PYTHON_MODULE_NAME)
    foreach(src IN LISTS OTHERS)
      get_filename_component(name "${src}" NAME)
      if(name MATCHES "^py.*\\.cpp$")
        list(APPEND PY_SRCS "${src}")
      endif()
    endforeach()
  endif()

  if(PACS_LIB_NAME)
    option(PACS_BUILD_SHARED "Build shared libraries" ON)
    option(PACS_BUILD_STATIC "Build static libraries" ON)

    if(PACS_BUILD_SHARED)
      add_library(${PACS_LIB_NAME} SHARED ${OTHERS})
      pacs_apply_common(${PACS_LIB_NAME})
      pacs_apply_deps(${PACS_LIB_NAME})
    endif()

    if(PACS_BUILD_STATIC)
      add_library(${PACS_LIB_NAME}_static STATIC ${OTHERS})
      set_target_properties(${PACS_LIB_NAME}_static PROPERTIES OUTPUT_NAME ${PACS_LIB_NAME})
      pacs_apply_common(${PACS_LIB_NAME}_static)
      pacs_apply_deps(${PACS_LIB_NAME}_static)
    endif()

    foreach(main IN LISTS MAINS)
      get_filename_component(exec_name "${main}" NAME_WE)
      add_executable(${exec_name} ${main})
      if(PACS_BUILD_SHARED)
        target_link_libraries(${exec_name} PRIVATE ${PACS_LIB_NAME})
      elseif(PACS_BUILD_STATIC)
        target_link_libraries(${exec_name} PRIVATE ${PACS_LIB_NAME}_static)
      endif()
      pacs_apply_common(${exec_name})
      pacs_apply_deps(${exec_name})
    endforeach()

    if(PACS_BUILD_SHARED)
      install(TARGETS ${PACS_LIB_NAME} LIBRARY DESTINATION lib)
    endif()
    if(PACS_BUILD_STATIC)
      install(TARGETS ${PACS_LIB_NAME}_static ARCHIVE DESTINATION lib)
    endif()
  else()
    set(EXEC_OBJ_TARGET "")
    if(OTHERS)
      if(PY_SRCS)
        set(OTHERS_NO_PY ${OTHERS})
        list(REMOVE_ITEM OTHERS_NO_PY ${PY_SRCS})
        if(OTHERS_NO_PY)
          add_library(pacs_obj OBJECT ${OTHERS_NO_PY})
          set(EXEC_OBJ_TARGET pacs_obj)
        endif()
      else()
        add_library(pacs_obj OBJECT ${OTHERS})
        set(EXEC_OBJ_TARGET pacs_obj)
      endif()
      if(EXEC_OBJ_TARGET)
        pacs_apply_common(${EXEC_OBJ_TARGET})
      endif()
    endif()

    foreach(main IN LISTS MAINS)
      get_filename_component(exec_name "${main}" NAME_WE)
      if(EXEC_OBJ_TARGET)
        add_executable(${exec_name} ${main} $<TARGET_OBJECTS:${EXEC_OBJ_TARGET}>)
      else()
        add_executable(${exec_name} ${main})
      endif()
      pacs_apply_common(${exec_name})
      pacs_apply_deps(${exec_name})
    endforeach()
  endif()

  if(PACS_PYTHON_MODULE_NAME)
    find_package(Python3 REQUIRED COMPONENTS Development.Module)
    set(PY_MODULE_SRCS ${OTHERS})
    if(PY_MODULE_SRCS)
      add_library(${PACS_PYTHON_MODULE_NAME} MODULE ${PY_MODULE_SRCS})
      pacs_apply_common(${PACS_PYTHON_MODULE_NAME})
      pacs_apply_deps(${PACS_PYTHON_MODULE_NAME})
      target_link_libraries(${PACS_PYTHON_MODULE_NAME} PRIVATE Python3::Module)
      set_target_properties(${PACS_PYTHON_MODULE_NAME} PROPERTIES PREFIX "")
      if(DEFINED Python3_EXTENSION_SUFFIX)
        set_target_properties(${PACS_PYTHON_MODULE_NAME} PROPERTIES SUFFIX "${Python3_EXTENSION_SUFFIX}")
      endif()
    endif()
  endif()

  pacs_install_headers()
endfunction()
