cmake_minimum_required(VERSION 3.20)

function(pacs_find_root out_var)
  set(dir "${CMAKE_CURRENT_LIST_DIR}")
  while(TRUE)
    if(EXISTS "${dir}/Makefile.inc" AND EXISTS "${dir}/src")
      set(${out_var} "${dir}" PARENT_SCOPE)
      return()
    endif()
    get_filename_component(parent "${dir}" DIRECTORY)
    if(parent STREQUAL dir)
      break()
    endif()
    set(dir "${parent}")
  endwhile()
  set(${out_var} "" PARENT_SCOPE)
endfunction()

function(pacs_setup_defaults)
  if(NOT PACS_ROOT)
    pacs_find_root(PACS_ROOT)
  endif()
  if(NOT PACS_ROOT)
    message(FATAL_ERROR "Could not find PACS_ROOT. Set -DPACS_ROOT=/path/to/Examples")
  endif()

  set(PACS_ROOT "${PACS_ROOT}" CACHE PATH "PACS examples root")

  if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set(CMAKE_INSTALL_PREFIX "${PACS_ROOT}" CACHE PATH "Install prefix" FORCE)
  endif()

  if(NOT CMAKE_CXX_STANDARD)
    set(CMAKE_CXX_STANDARD 23)
  endif()
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  set(CMAKE_CXX_EXTENSIONS OFF)

  add_compile_options(-Wall -Wextra -Wsuggest-override -Wnon-virtual-dtor)

  if(CMAKE_BUILD_TYPE STREQUAL "Release")
    add_compile_definitions(NDEBUG)
  endif()

  if(NOT EIGEN_DIR)
    set(EIGEN_DIR "/usr/local/include/eigen3" CACHE PATH "Eigen include directory")
  endif()
endfunction()

function(pacs_apply_common target)
  target_include_directories(${target}
    PRIVATE
      "${CMAKE_CURRENT_LIST_DIR}"
      "${CMAKE_CURRENT_LIST_DIR}/include"
      "${PACS_ROOT}/include"
      "${EIGEN_DIR}"
  )
  if(PACS_EXTRA_INCLUDE_DIRS)
    target_include_directories(${target} PRIVATE ${PACS_EXTRA_INCLUDE_DIRS})
  endif()
endfunction()

function(pacs_link_pacs_lib target)
  find_library(PACS_LIBRARY pacs PATHS "${PACS_ROOT}/lib")
  if(NOT PACS_LIBRARY)
    message(FATAL_ERROR "libpacs not found in ${PACS_ROOT}/lib")
  endif()
  target_link_libraries(${target} PRIVATE "${PACS_LIBRARY}")
endfunction()

function(pacs_apply_deps target)
  if(PACS_USE_MPI)
    find_package(MPI REQUIRED)
    target_link_libraries(${target} PRIVATE MPI::MPI_CXX)
  endif()

  if(PACS_USE_OPENMP)
    find_package(OpenMP REQUIRED)
    target_link_libraries(${target} PRIVATE OpenMP::OpenMP_CXX)
  endif()

  if(PACS_USE_TBB)
    find_package(TBB REQUIRED)
    target_link_libraries(${target} PRIVATE TBB::tbb)
  endif()

  if(PACS_USE_BOOST)
    find_package(Boost REQUIRED COMPONENTS iostreams filesystem system)
    target_link_libraries(${target} PRIVATE Boost::iostreams Boost::filesystem Boost::system)
  endif()

  if(PACS_USE_HDF5)
    find_package(HDF5 REQUIRED)
    target_include_directories(${target} PRIVATE ${HDF5_INCLUDE_DIRS})
    target_link_libraries(${target} PRIVATE ${HDF5_LIBRARIES})
  endif()

  if(PACS_USE_BLAS)
    find_package(BLAS REQUIRED)
    if(TARGET BLAS::BLAS)
      target_link_libraries(${target} PRIVATE BLAS::BLAS)
    else()
      target_link_libraries(${target} PRIVATE ${BLAS_LIBRARIES})
    endif()
  endif()

  if(PACS_USE_MUPARSER)
    find_library(MUPARSER_LIBRARY muparser PATHS "${PACS_ROOT}/lib")
    find_library(MUPARSERX_LIBRARY muparserx PATHS "${PACS_ROOT}/lib")
    if(NOT MUPARSER_LIBRARY)
      message(FATAL_ERROR "muparser not found in ${PACS_ROOT}/lib")
    endif()
    if(NOT MUPARSERX_LIBRARY)
      message(FATAL_ERROR "muparserx not found in ${PACS_ROOT}/lib")
    endif()
    target_include_directories(${target} PRIVATE "${PACS_ROOT}/include/muparserx")
    target_link_libraries(${target} PRIVATE ${MUPARSER_LIBRARY} ${MUPARSERX_LIBRARY})
  endif()

  if(PACS_USE_DL)
    target_link_libraries(${target} PRIVATE ${CMAKE_DL_LIBS})
  endif()

  if(PACS_LINK_PACS)
    pacs_link_pacs_lib(${target})
  endif()

  if(PACS_EXTRA_COMPILE_OPTIONS)
    target_compile_options(${target} PRIVATE ${PACS_EXTRA_COMPILE_OPTIONS})
  endif()
  if(PACS_EXTRA_DEFINITIONS)
    target_compile_definitions(${target} PRIVATE ${PACS_EXTRA_DEFINITIONS})
  endif()
  if(PACS_EXTRA_LINK_OPTIONS)
    target_link_options(${target} PRIVATE ${PACS_EXTRA_LINK_OPTIONS})
  endif()
  if(PACS_EXTRA_LIBS)
    target_link_libraries(${target} PRIVATE ${PACS_EXTRA_LIBS})
  endif()

  if(PACS_LINK_LIB_NAMES)
    foreach(libname IN LISTS PACS_LINK_LIB_NAMES)
      find_library(PACS_FOUND_LIB_${libname} ${libname} PATHS "${PACS_ROOT}/lib")
      if(PACS_FOUND_LIB_${libname})
        target_link_libraries(${target} PRIVATE ${PACS_FOUND_LIB_${libname}})
      else()
        message(FATAL_ERROR "Library ${libname} not found in ${PACS_ROOT}/lib")
      endif()
    endforeach()
  endif()
endfunction()
