CXX       ?= g++
CXXFLAGS  ?= -std=c++11 
CPPFLAGS  ?= -I. -Wno-conversion-null -Wno-deprecated-declarations
LDFLAGS   ?= 
LIBS      ?= 

all : newton_example

newton_example : #dependencies
	#rules

clean :
	$(RM) *.o

distclean : clean
	$(RM) $(EXEC) $(EXECMP)


