#
# Users have to cahncge this
#

# Directory where libumfpack is stored, use the syntax -LdirectoryName
UMFPACK_DIR=# -LDirectoryOfUmfpackLib
# Directory where umfpack.h is stored
UMFPACK_INCDIR=/usr/include/suitesparse
